default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnpool_development

test:
  <<: *default
  database: airbnpool_test

production:
  <<: *default
  url: <%= ENV['postgresql://u8jw7b2dhxlyszvnlmwu:NIGprEac6mdF4OnaFU1M@bi6mpncrmvzaxsodairu-postgresql.services.clever-cloud.com:5432/bi6mpncrmvzaxsodairu'] %>
